#!/usr/bin/env bash
# display "To infinity and beyond" indefinitely while sleeping every 2 seconds and "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
